name: Build kernel for beyond1lte

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get kernel source
        uses: actions/checkout@v3
        with:
          repository: linux4-bringup-priv/android_kernel_samsung_exynos9820
          ref: lineage-21.0
          path: kernel
          fetch-depth: 100

      - name: Get GCC toolchain
        uses: actions/checkout@v3
        with:
          repository: mvaisakh/gcc-arm64
          ref: 05cb20a52f12389c3f2340b5103485108feae302
          path: toolchain

      - name: Integrate KernelSU
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Show paths
        run: |
          echo "**** toolchain:"
          find ~/toolchain
          echo "**** kernel:"
          find ~/kernel
          false

      - name: Build kernel
        env:
          CC: gcc
          ARCH: arm64
          SUBARCH: arm64
          CROSS_COMPILE: ~/toolchain/bin/aarch64-elf-
        run: |
          sudo apt install -y binutils
          cd kernel
          PATH="$HOME"/toolchain/bin:"$PATH"
          export CC ARCH SUBARCH CROSS_COMPILE
          make O=out "exynos9820-beyond1lte_defconfig"
          make -j$(nproc --all) O=out prepare
          make -j$(nproc --all) O=out
