name: Build kernel for beyond1lte

on:
  push:
  workflow_dispatch:

env:
  KPATH: /home/runner/work/ksu-beyond1/ksu-beyond1/kernel
  TPATH: /home/runner/work/ksu-beyond1/ksu-beyond1/toolchain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get kernel source
        uses: actions/checkout@v3
        with:
          repository: linux4-bringup-priv/android_kernel_samsung_exynos9820
          ref: lineage-21.0
          path: /home/runner/work/ksu-beyond1/ksu-beyond1/kernel
          fetch-depth: 100

      - name: Get clang toolchain
        run: |
          sudo apt install linux-libc-dev-arm64-cross flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev python-all-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar gcc-10 g++-10 zstd -y --fix-broken --fix-missing
          mkdir $TPATH
          curl -Lso- https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r510928.tar.gz | gunzip | tar -xv -C $TPATH

      - name: Integrate KernelSU
        run: |
          cd $KPATH
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Build kernel
        env:
          CC: clang
          ARCH: arm64
          SUBARCH: arm64
        run: |
          cd $KPATH
          export PATH="$HOME"/toolchain/bin:"$PATH"
          export CC ARCH
          make CC=$CC O=out "exynos9820-beyond1lte_defconfig"
          make -j$(nproc --all) CC=$CC O=out
          mv out/arch/arm64/boot/Image.gz* ~

      - name: Upload compiled kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel
          path: /home/runner/Image.gz-dtb
