name: beyond1lte

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install flex bison ncurses-dev texinfo gcc gperf patch libtool \
           automake g++ libncurses5-dev gawk subversion expat libexpat1-dev \
           python-all-dev binutils-dev bc libcap-dev autoconf libgmp-dev \
           build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man \
           liblzma-dev libssl-dev libz-dev mercurial wget tar gcc-10 g++-10 zstd \
           libarchive-tools tree \
            -y --fix-broken --fix-missing

      - name: Clone kernel source
        uses: actions/checkout@v3
        with:
          repository: LineageOS/android_kernel_samsung_exynos9820
          path: /home/runner/work/ksu-beyond1/ksu-beyond1

      - name: Clone toolchain
        uses: actions/checkout@v3
        with:
          repository: kdrag0n/proton-clang
          path: /home/runner/work/ksu-beyond1/ksu-beyond1/toolchain

      - name: Clone patches
        uses: actions/checkout@v3
        with:
          repository: alemontn/ksu-beyond1
          path: /home/runner/work/ksu-beyond1/ksu-beyond1/patches

      - name: Integrate KernelSU
        run: |
          cd ~/work/ksu-beyond1/ksu-beyond1
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
          git config --global user.email "20985102-alemontn@users.noreply.gitlab.com"
          git config --global user.name "ethyl"
          git add . || true
          git commit -a -m "add KernelSU"

      - name: Apply patches
        run: |
          cd ~/work/ksu-beyond1/ksu-beyond1
          git apply patches/patches/*.patch
          git commit -a -m "apply patches"

      - name: Show directory tree
        run: tree ~ >~/tree.log

      - name: Build kernel
        env:
          CC: clang
          CROSS_COMPILE: aarch64-linux-gnu-
          ARCH: arm64
          SUBARCH: arm64
        run: |
          cd ~/work/ksu-beyond1/ksu-beyond1
          export PATH=~/work/ksu-beyond1/ksu-beyond1/toolchain/bin:"$PATH"
          export CC CROSS_COMPILE ARCH SUBARCH
          defconfig="exynos9820-beyond1lte_defconfig"
          make CC=$CC O=out "$defconfig"
          make -j$(nproc --all) CC=$CC O=out
          mv out/arch/arm64/boot/Image.gz ~

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: /home/runner/*.log

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: kernel
          path: /home/runner/Image.gz
